Repository UCF/Search-Service-Django, pull requests merged in 2019-11, with the labels that each got.

#38 Teledata
  requirements.txt
  settings.py
  settings_local.tmpl.py
  teledata/__init__.py
  teledata/admin.py
  teledata/apps.py
  teledata/management/__init__.py
  teledata/management/commands/__init__.py
  teledata/management/commands/import-teledata.py
  teledata/migrations/0001_initial.py
  teledata/migrations/0002_auto_20191028_1522.py
  teledata/migrations/0003_auto_20191031_1600.py
  teledata/migrations/0004_combinedteledataview.py
  teledata/migrations/0005_auto_20191104_1429.py
  teledata/migrations/__init__.py
  teledata/models.py
  teledata/tests.py
  teledata/views.py
Labels: enhancement

#39 Add Teledata Buildings View
  programs/urls.py
  settings.py
  teledata/serializers.py
  teledata/urls.py
  teledata/views.py
  urls.py
Labels: enhancement

#40 Optimized search
  teledata/models.py
Labels: enhancement

#41 Updated query to properly execute like statements
  teledata/models.py
Labels: enhancement

#42 Create Teledata Views for Departments, Staff, and Organizations
  teledata/migrations/0006_auto_20191106_1512.py
  teledata/models.py
  teledata/serializers.py
  teledata/urls.py
  teledata/views.py
Labels: enhancement

#43 Teledata view
  requirements.txt
  settings.py
  teledata/filters.py
  teledata/management/commands/import-teledata.py
  teledata/migrations/0007_auto_20191107_1553.py
  teledata/migrations/0008_auto_20191107_1951.py
  teledata/migrations/0009_auto_20191108_1358.py
  teledata/migrations/0010_auto_20191108_1619.py
  teledata/models.py
  teledata/serializers.py
  teledata/urls.py
  teledata/views.py
Labels: enhancement

#44 Keywords
  teledata/admin.py
  teledata/migrations/0011_keyword.py
  teledata/migrations/0012_combinedteledata_keywords_combined.py
  teledata/models.py
Labels: enhancement

#49 Keywords fix
  teledata/admin.py
  teledata/models.py
Labels: bug, enhancement

#50 Hot Fix CORS and Pagination
  requirements.txt
  settings.py
  teledata/pagination.py
  teledata/views.py
Labels: bug

#55 Added CIP code column to programs
  programs/migrations/0019_program_cip_code.py
  programs/models.py
Labels: enhancement

#58 Outcomes data
  programs/admin.py
  programs/migrations/0020_academicyear_programoutcomestat.py
  programs/migrations/0021_auto_20191125_2020.py
  programs/models.py
  programs/serializers.py
Labels: enhancement

#59 CIP imports
  programs/management/commands/import-programs.py
Labels: enhancement

#60 Added CIP values to API results
  programs/serializers.py
Labels: enhancement

#61 Updated combined search view to order by id when no query is made
  teledata/views.py
Labels: bug
