Repository UCF/Search-Service-Django, pull requests merged in 2020-01, with the labels that each got.

#75 Lowering email before importing
  teledata/management/commands/import-teledata.py
Labels: bug

#93 Simple feed
  programs/serializers.py
  programs/urls.py
  programs/views.py
Labels: bug, enhancement

#96 Frontend synonyms
  images/management/commands/import-tandemvault-images.py
  images/management/commands/import-tandemvault-tags.py
Labels: enhancement

#97 Non-symmetrical synonyms
  images/models.py
  images/serializers.py
Labels: enhancement

#98 Threaded import
  images/management/commands/import-tandemvault-images.py
Labels: enhancement

#102 Added logic for searching by phone number
  teledata/models.py
Labels: enhancement

#112 Ensure the tandemvault image importer only processes images
  images/management/commands/import-tandemvault-images.py
Labels: enhancement

#121 Implemented basic scoring system for image search results
  images/models.py
  images/serializers.py
  images/views.py
Labels: enhancement

#124 CORS Fix
  settings.py
Labels: bug

#123 Image search docs
  templates/home.html
Labels: documentation

#127 Single profile field
  programs/management/commands/process-profiles.py
  programs/models.py
  programs/serializers.py
  settings_local.tmpl.py
Labels: enhancement

#128 External Profile Import
  programs/management/commands/import-profiles.py
Labels: enhancement

#130 Profile Importer Updates
  programs/management/commands/import-profiles.py
Labels: enhancement
