Repository UCF/Search-Service-Django, pull requests merged in 2024-06, with the labels that each got.

#422 Added hook to ensure audit data gets added on program create
  programs/models.py
Labels: bug

#424 Dependency Tracking Update
  README.md
  dev-requirements.txt
  requirements.txt
  setup.py
Labels: enhancement, documentation, dependencies

#425 Fontawesome 6 pro added to the project.
  .gitignore
  README.md
  gulpfile.js
  package-lock.json
  package.json
  src/scss/_font-awesome-config.scss
  static/css/style.min.css
  static/webfonts/fa-brands-400.ttf
  static/webfonts/fa-brands-400.woff2
  static/webfonts/fa-duotone-900.ttf
  static/webfonts/fa-duotone-900.woff2
  static/webfonts/fa-light-300.ttf
  static/webfonts/fa-light-300.woff2
  static/webfonts/fa-regular-400.ttf
  static/webfonts/fa-regular-400.woff2
  static/webfonts/fa-sharp-light-300.ttf
  static/webfonts/fa-sharp-light-300.woff2
  static/webfonts/fa-sharp-regular-400.ttf
  static/webfonts/fa-sharp-regular-400.woff2
  static/webfonts/fa-sharp-solid-900.ttf
  static/webfonts/fa-sharp-solid-900.woff2
  static/webfonts/fa-sharp-thin-100.ttf
  static/webfonts/fa-sharp-thin-100.woff2
  static/webfonts/fa-solid-900.ttf
  static/webfonts/fa-solid-900.woff2
  static/webfonts/fa-thin-100.ttf
  static/webfonts/fa-thin-100.woff2
  static/webfonts/fa-v4compatibility.ttf
  static/webfonts/fa-v4compatibility.woff2
  template.npmrc
Labels: enhancement
