Repository UCF/Search-Service-Django, pull requests merged in 2024-07, with the labels that each got.

#428 pulling highlight Json in views.py
  core/views.py
  src/js/highlights-iconpicker.js
  static/js/fontawesome-v6.4.2.json
  static/js/highlights-iconpicker.min.js
  templates/dashboard/program-edit.html
Labels: enhancement

#429 Storing highlights in database + Id replaced with data-order in JS part
  core/views.py
  programs/migrations/0059_program_highlights.py
  programs/models.py
  src/js/highlights-iconpicker.js
  static/js/highlights-iconpicker.min.js
Labels: enhancement

#430 Highlights frontend
  core/views.py
  src/js/highlights-iconpicker.js
  static/js/highlights-iconpicker.min.js
Labels: enhancement, javascript, python

#432 Usage report
  core/urls.py
  core/views.py
  templates/dashboard/usage-report.html
Labels: enhancement

#436 Jobs Audit Data and Usage Report Update
  core/models.py
  core/templatetags/core_extras.py
  core/views.py
  programs/models.py
  templates/dashboard/home.html
  templates/dashboard/usage-report.html
Labels: enhancement

#437 Closing modal
  templates/dashboard/program-edit.html
Labels: enhancement

#438 Jobs are not required. Everyone eats for free
  core/forms.py
Labels: bug

#439 Sortable Library Swap
  src/js/script.js
  src/js/sortable.js
  src/scss/sortable/_sortable.sass
  src/scss/sortable/sortable-theme-bootstrap.sass
  src/scss/sortable/sortable-theme-dark.sass
  src/scss/sortable/sortable-theme-finder.sass
  src/scss/sortable/sortable-theme-light.sass
  src/scss/sortable/sortable-theme-minimal.sass
  src/scss/sortable/sortable-theme-slick.sass
  src/scss/style.scss
  static/css/style.min.css
  static/js/script.min.js
  templates/dashboard/usage-report.html
Labels: enhancement

#440 Updates
  dev-requirements.txt
  requirements.txt
Labels: dependencies
