Repository UCF/Search-Service-Django, pull requests merged in 2025-02, with the labels that each got.

#460 Tagify Implementation - Career Paths Section
  core/forms.py
  gulpfile.js
  src/js/jobs-tagify.js
  src/js/jobs-typeahead.js
  src/scss/_base.scss
  static/css/style.min.css
  static/js/jobs-tagify.min.js
  static/js/jobs-typeahead.min.js
  templates/dashboard/program-edit.html
Labels: enhancement, dependencies

#461 Current CIP Property Bug
  programs/models.py
Labels: bug

#462 Project Cleanup
  dev-requirements.txt
  programs/migrations/0031_auto_20191206_1459.py
  pyproject.toml
  requirements.txt
  teledata/migrations/0005_auto_20191104_1429.py
  teledata/migrations/0008_auto_20191107_1951.py
  teledata/migrations/0009_auto_20191108_1358.py
Labels: bug

#466 Catalog Matching Logic Update
  programs/utilities/catalog_match.py
Labels: bug

#465 Fixed the format of the output - Career paths field
  src/js/jobs-tagify.js
  static/js/jobs-tagify.min.js
Labels: bug

#468 Quote model
  .gitignore
  marketing/__init__.py
  marketing/admin.py
  marketing/apps.py
  marketing/migrations/0001_initial.py
  marketing/migrations/0002_rename_speaker_quote_source.py
  marketing/migrations/__init__.py
  marketing/models.py
  marketing/tests.py
  marketing/views.py
  media/.gitkeep
  settings.py
  settings_local.tmpl.py
  urls.py
  uv.lock
Labels: enhancement

#469 Added API endpoints for CRUD operations on quotes
  marketing/filters.py
  marketing/models.py
  marketing/parsers.py
  marketing/serializers.py
  marketing/urls.py
  marketing/views.py
  urls.py
Labels: enhancement

#470 Added Tags to Quotes
  dev-requirements.txt
  marketing/migrations/0003_quote_tags.py
  marketing/models.py
  marketing/serializers.py
  pyproject.toml
  requirements.txt
  settings.py
Labels: enhancement
