Repository UCF/Search-Service-Django, pull requests merged in 2025-01, with the labels that each got.

#447 Package Updates and Migration Fix
  core/filters.py
  core/migrations/0001_initial.py
  pyproject.toml
  requirements.txt
Labels: bug

#449 Filters!
  core/filters.py
Labels: bug

#450 Catalog Import Update
  programs/management/commands/import-catalog-descriptions.py
Labels: bug

#452 Highlights edits
  src/js/highlights-iconpicker.js
  static/js/highlights-iconpicker.min.js
  templates/dashboard/program-edit.html
Labels: enhancement

#453 Highlights modal
  src/js/highlights-iconpicker.js
  static/js/highlights-iconpicker.min.js
  templates/dashboard/program-edit.html
Labels: enhancement

#457 Submit bug
  programs/migrations/0064_alter_programauditdata_jobs_source.py
  programs/models.py
  src/js/highlights-iconpicker.js
  src/js/jobs-typeahead.js
  static/js/highlights-iconpicker.min.js
  static/js/jobs-typeahead.min.js
  templates/dashboard/program-edit.html
Labels: bug, enhancement

#458 made the field empty after token created.
  src/js/jobs-typeahead.js
  static/js/jobs-typeahead.min.js
Labels: bug
